### ISSUE TITLE
Dependency on deep-freeze seems to confuse SystemJS

### ISSUE THREAD

**Issue by brian428** [brandonroberts/ngrx-store-freeze#3] opened 2016-09-28 21:40 UTC
I've got a project using ngrx and ngrx-store-freeze. But the dependency on deep-freeze seems to be confusing SystemJS.

If I use this in my SystemJS Builder configuration for packages: 

```
{
  '@ngrx/core': {
    main: 'index.js',
    defaultExtension: 'js'
  },
  '@ngrx/store': {
    main: 'index.js',
    defaultExtension: 'js'
  },
  'ngrx-store-freeze': {
    main: 'dist/index.js',
    defaultExtension: 'js'
  }
}
```

I get an error during the build:

```
Error on fetch for deep-freeze.js at file:///C:/Developer/Projects/ngrx-tests/node_modules/deep-freeze.js
        Loading ngrx-store-freeze/dist/index.js
```

But if I manually add deep-freeze to the SystemJS packages, it finds it OK.

So I've got it working, but it seems very odd that I would have to manually add this package mapping for an internal dependency of a Node module. Is this normal/expected behavior? Or am I just doing something wrong?

**Comment by tsm91** [comment] 2016-10-11 08:33
Hi @brian428. I have no idea, never used SystemJS before.

ping @btroncone

If i remember correct i modeled this project based on `ngrx-store-logger`. Do you have any experience with SystemJS? Have you ran into similar issues?

**Comment by brian428** [comment] 2016-10-11 13:20
I have some experience with it (from using the Angular 2 Seed project), but not a lot I'm afraid. I do know that *most* projects don't require adding transitive dependencies manually, because that would obviously turn into a total nightmare. But what the magic incantation is to handle this, I'm not sure.

If no one else runs into this or is bothered by it, we can probably close the issue. It's not a big problem, it just struck me as odd and I was hoping it might be something simple that I (or you) just weren't aware of.

**Comment by tsm91** [comment] 2016-10-13 11:16
alright :D 

I'll leave this issue open for now anyways. Whatever the problem is, it is not solved and maybe others experience it as well.

**Comment by amariniello** [comment] 2016-11-03 11:34
Just bumped in the same issue here. but from my experience we must add that dependency declaration to the System.js config. how would System.js be able to resolve the deep-freeze dependency without having it declared anywhere? maybe a note should be added in the wiki for System.js users

**Comment by brandonroberts** [comment] 2017-09-25 01:07
Closing as this project no longer depends on `deep-freeze`

**Closed by brandonroberts** 2017-09-25 01:07 UTC
Labels: help wanted, question
