### ISSUE TITLE
Update to NgRx 4

### ISSUE THREAD

**Issue by StevenLiekens** [brandonroberts/ngrx-store-freeze#17] opened 2017-07-19 12:21 UTC
It appears that ngrx-store-freeze is incompatible with NgRx 4.

**Comment by DorianGrey** [comment] 2017-07-20 11:35
To be a bit more precise:
I've seen this issue as well while updating my template to ngrx4. It seems that parameters accessed by zone.js get freezed as well. At least that's what the browser console mentions:
```
TypeError: Cannot assign to read only property 'microTask' of object '[object Object]'
    at ZoneDelegate._updateTaskCount (polyfills.dll.js:5603)
    at Zone._updateTaskCount (polyfills.dll.js:5438)
    at Zone.runTask (polyfills.dll.js:5358)
    at drainMicroTaskQueue (polyfills.dll.js:5745)
    at <anonymous>

Uncaught TypeError: Cannot assign to read only property 'macroTask' of object '[object Object]'
    at ZoneDelegate._updateTaskCount (http://localhost:9987/polyfills.dll.js:5603:37)
    at Zone._updateTaskCount (http://localhost:9987/polyfills.dll.js:5438:34)
    at Zone.scheduleTask (http://localhost:9987/polyfills.dll.js:5397:22)
    at Zone.scheduleMacroTask (http://localhost:9987/polyfills.dll.js:5408:25)
    at http://localhost:9987/polyfills.dll.js:7009:33
    at proto.(anonymous function) (http://localhost:9987/polyfills.dll.js:6371:20)
    at XHRLocalObject.AbstractXHRObject (http://localhost:9987/polyfills.dll.js:4184:3)
    at new XHRLocalObject (http://localhost:9987/polyfills.dll.js:2208:13)
    at new InfoAjax (http://localhost:9987/polyfills.dll.js:4779:13)
    at Function.InfoReceiver._getReceiver (http://localhost:9987/polyfills.dll.js:11380:12)

Uncaught Error: macroTask 'setTimeout': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.
    at ZoneTask._transitionTo (polyfills.dll.js:5682)
    at Zone.runTask (polyfills.dll.js:5331)
    at ZoneTask.invokeTask (polyfills.dll.js:5648)
    at ZoneTask.invoke (polyfills.dll.js:5637)
    at timer (polyfills.dll.js:6973)
```

Steps to reproduce:
- Checkout https://github.com/DorianGrey/ng-webpack-template/tree/ngrx-4-update .
- Uncomment [this line](https://github.com/DorianGrey/ng-webpack-template/blob/ngrx-4-update/src/app/app.store.ts#L10).
- Add `storeFreeze` to the array [here](https://github.com/DorianGrey/ng-webpack-template/blob/ngrx-4-update/src/app/app.store.ts#L100).
- `yarn && yarn start` resp. `npm i && npm start`.

**Comment by dojchek** [comment] 2017-07-24 17:02
@DorianGrey 
I'm getting the same exception.. All I do is simply provide 'storeFreeze' as meta-reducer:
```
StoreModule.forRoot(reducers, {
      metaReducers: [storeFreeze]
    }),
```

**Comment by DorianGrey** [comment] 2017-07-24 19:27
Ok... I've debugged this a little bit, and it seems to have something to do with parameter added by [@ngrx/router-store](https://github.com/ngrx/platform/tree/master/modules/router-store). These parameters may contain a router snapshot and additional linked data, and you may guess what happens when these get frozen.

Unfortunately, this means that not only some parameters of the state have to be skipped - even some dispatched actions have to be ignored completely.

I've hacked a solution for this, though I'm not that lucky with it:
```typescript
import {Action, ActionReducer} from "@ngrx/store";

/**
 * A list of properties to ignore when deep-freezing.
 * Contains arguments that must not be modified in strict mode in general
 * (caller, callee, arguments) plus the `router` argument, which is added by @ngrx/router-store.
 */
const propBlackList: string[] = ["caller", "callee", "arguments", "router"];

/**
 * A regular expression to match `action.type` against.
 * Some actions have to be ignored in general, since freezing
 * any parts of them has undesirable side-effects.
 */
const ignoreActionsRegex: RegExp = /^(ROUTER?_|@ngrx)/;

function deepFreeze(o: any): void {
  Object.freeze(o);
  const hasOwnProp = Object.prototype.hasOwnProperty;
  Object
    .getOwnPropertyNames(o)
    .filter(p => propBlackList.indexOf(p) === -1)
    .forEach(prop => {
    if (hasOwnProp.call(o, prop)
      && o[prop] !== null
      && (typeof o[prop] === "object" || typeof o[prop] === "function")
      && !Object.isFrozen(o[prop])) {
      deepFreeze(o[prop]);
    }
  });

  return o;
}

export function storeFreeze(reducer: ActionReducer<any>): ActionReducer<any> {
  return function (state: any, action: Action) {
    if (ignoreActionsRegex.test(action.type)) {
      return reducer(state, action);
    } else {
      state && deepFreeze(state);
      // Ignore null/undefined values.
      if ((action as any).payload != null) {
        deepFreeze((action as any).payload);
      }
      const nextState = reducer(state, action);
      nextState && deepFreeze(nextState);
      return nextState;
    }
  };
}
```
Primary concern is configuration - the `router` field is the name of the `routerReducer` entry in my state definition, and thus may vary for other users. Already tried some things, but AoT did not like any of them...

Oh, and just for completeness: The above is a variant of this library and the underlying `deep-freeze-strict`. Had to modify both of them to make things work for now.

Just hope anyone has got a better idea than this hack, although I fear there are not that many solutions for this problem ...

**Comment by lekhnath** [comment] 2017-08-03 05:18
when will suport for ngrx v4 land?

**Comment by dojchek** [comment] 2017-08-03 09:31
I think that we just have to wait for router-state serializer to be done.
https://github.com/ngrx/platform/pull/188#discussion_r131037129

Once in, it should fix the following issue (which is pretty much the issue we are having here):
https://github.com/ngrx/platform/issues/104

If you leave the router-store out outside of store, storeFreeze should work.

**Comment by LMFinney** [comment] 2017-08-07 20:22
Note: we're having the same problem, even though we're not using @ngrx/router-store.

**Comment by strizzaflex** [comment] 2017-08-10 11:47
There is a workaround that was merged into trunk of router-store. It's in the nightly build and should be in the next release. 

[ngrx/platform#188 - pull](https://github.com/ngrx/platform/pull/188)

**Comment by timbru31** [comment] 2017-08-17 15:24
Besides that, I'm receiving an `UNMET PEER DEPENDENCY @ngrx/store@4.0.3`, because ngrx-store-freeze defines `v2.2.1`
```shell
npm WARN ngrx-store-freeze@0.1.9 requires a peer of @ngrx/store@^2.2.1 but none was installed.
```

**Comment by dojchek** [comment] 2017-09-11 09:06
Hey guys,
Any update on this one?

**Comment by tsm91** [comment] 2017-09-13 18:41
can somebody issue a pull request please?

i no longer keep playing with angular && the ecosystem. but i feel bad about these issues, cmon guys make a pull request :dancer: 

also **looking for maintainer** because of the reaons mentioned above

**Comment by StevenLiekens** [comment] 2017-09-13 21:02
@tsm91, perhaps you can start a fundraiser to resolve this issue? Make it worth your time.

**Comment by LMFinney** [comment] 2017-09-14 14:02
@DorianGrey's suggestion makes sense as a workaround for an individual, but I don't think it should be pulled into the library, because it would secretishly disable freezing for any properties named "caller", "callee", "arguments", or "router". There's bound to be other programmers that would use those names at some point.

Isn't the core message here that the @ngrx router is mutating things that it shouldn't? Perhaps this metareducer is doing the right thing, and @ngrx itself is what needs to change.

I mentioned above that my team was seeing the same problem, and I'm pretty sure it's because we use wrapped kendo jquery widgets, and those widgets mutate objects that they receive. So, it was either our mistake in sending the original store objects that should have been mutated to kendo, or kendo's mistake for assuming that it could mutate what it received. Either way, it wasn't the fault of ngrx-store-freeze.

**Comment by DorianGrey** [comment] 2017-09-14 16:31
>  because it would secretishly disable freezing for any properties named "caller", "callee", "arguments", or "router".

Just a note - I did not add the first three of that list for no reason: These properties exist on a function object and everything that derives from it. In any code that runs in strict mode, accessing these parameters is restricted, and may throw errors when attempting to freeze them. That is why these parameters are skipped in the [deep-freeze](https://github.com/jsdf/deep-freeze/blob/master/index.js) library used by this project as well (missed the `isFunction` check in my hack, of course).

>  Isn't the core message here that the @ngrx router is mutating things that it shouldn't? 

The library itself does not mutate parts of the provided state. The problems described above refer to an issue about storing objects (here: from zone.js) that have to be mutatable from outside, and thus cannot be frozen.

> Perhaps this metareducer is doing the right thing, and @ngrx itself is what needs to change.

That already happend - the problem originially described here was cause by `ngrx/router-store`, which stores a router snapshot. However, that snapshot referenced a lot of stuff that cannot be frozen safely.
That's why the ability to provide a custom state serializer was introduced recently:
https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer
By providing one, it is possible to only use a part of the snapshot, e.g. the route name and query parameters, thus skipping parameters that may not be frozen safely. The only "issue" that still remains is the warning about the mismatching peer dependency:
```ngrx-store-freeze@0.1.9 requires a peer of @ngrx/store@^2.2.1 but none was installed.```

> So, it was either our mistake in sending the original store objects that should have been mutated to kendo, or kendo's mistake for assuming that it could mutate what it received.

The store content is intended to be immutable - it would not make sense to try to freeze the content explicitly if there is still code that attempts to mutate the objects it receives. So this sounds like a misuse in general, and not a problem of the store or the freeze meta reducer.

**Comment by brandonroberts** [comment] 2017-09-25 02:05
Version `0.2.0` has been released with support for NgRx V4.x

**Closed by brandonroberts** 2017-09-25 02:05 UTC

**Comment by colinskow** [comment] 2017-09-25 06:54
Well done for the great work @brandonroberts! Just one remaining issue: there is still a conflict with @ngrx/router-store. The `router-store` contains mutating objects. This needs to be excluded from the freeze, or `router-store` needs to be fixed to not contain mutating objects.

**Comment by zakhenry** [comment] 2017-09-25 09:29
@colinskow you should consider using a custom serializer with the router store as the router state has huge performance impact on ngrx due to the huge default size. This was the cause of the issue with the devtools bogging down with performance. See https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer

**Comment by colinskow** [comment] 2017-09-25 10:47
@zakhenry thank you very much! It's now working perfectly. These instructions definitely need to be added to the docs because a lot of people are going to have this problem.

**Comment by zakhenry** [comment] 2017-09-25 12:32
@colinskow no problem, docs updated in https://github.com/ngrx/platform/pull/426

**Comment by brandonroberts** [comment] 2017-09-25 12:44
I also added some docs in the README about `@ngrx/router-store`  via #21

**Comment by markoffden** [comment] 2018-03-23 13:17
Hmmm... for me issue is back after updating to NgRx 5.0, my ngrx-store-freeze version is 0.2.1

**Comment by duartealexf** [comment] 2018-09-05 02:28
Issue still exists on ngrx 6.

**Comment by Frayion** [comment] 2019-09-24 15:53
I am getting the same issue when using dispatch action, i cannot mutate property in my component to be pass inside dispatch.
ngrx 7 and ngrx-store-freeze 0.2.4
